server:
  port: 8091
spring:
  profiles:
    active: DEV
---
server:
  port: 809
spring:
  application:
    name: money
  profiles: PROD
---
spring:
  application:
    name: MONEY DEV
  profiles: DEV

publisher:
  time:
    threads: 10