server:
  port: 8091
spring:
  profiles:
    active: DEV
---
server:
  port: 8090
spring:
  application:
    name: money
  profiles: PROD
---
spring:
  application:
    name: MONEY DEV
  profiles: DEV